apiVersion: v1
entries:
  openprovider-webhook:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2021-06-02T16:10:09.420319+02:00"
    description: A Helm chart for Kubernetes
    digest: 7f0c13fe013c7f5c64011b2eda758699b7e371fde31762bb2e3935ec6fdbd149
    name: openprovider-webhook
    urls:
    - https://github.com/ontola/openprovider-webhook/releases/download/openprovider-webhook-0.1.0/openprovider-webhook-0.1.0.tgz
    version: 0.1.0
generated: "2021-06-02T16:10:09.420327+02:00"
